### ISSUE TITLE
Docker migrations don't seem to run anymore.

### ISSUE THREAD

**Issue by elorest** [TechMagister/kemalyst-generator#35]
It's really weird because last night docker ran perfectly for me on both pg and mysql. For some reason now the migrations don't get run. Not sure what could have changed between now and then. Perhaps something with the docker image? 

I went through and cleaned up the docker file and added options to that sqlite works. Went to test that all 3 still worked in docker and it was broken. I've spend 3 hours trying to get to the bottom of it but all I can figure out is that migrate isn't happening although it still works fine with `kgen m up` if I run it locally. Ran a shell inside the docker image and `kgen m up` exited without any messages.

**Comment by elorest** [comment]
Seems to just be an issue with table already existing in volume.

**Comment by drujensen** [comment]
@elorest how did you resolve this?  I'm having the same issue.

**Comment by drujensen** [comment]
also, do you mind if I change the db flag to `-d` instead of `--db`?

I added support for `ecr` templates and want to use `-t`

https://github.com/TechMagister/kemalyst-generator/pull/34

**Comment by elorest** [comment]
Yeah -d sounds great. I also add a flag called --deps while I was making sqlite work. 
I spent 4 hours from midnight til 4AM trying to make docker work again. I'm super confused on that. It actually started working for me like 10 times in a row so I closed the ticket and it immediately came back. Like some sort of ghost in the machine. :(. It seems to be some sort of issue with loading precedence or something. Sometimes the migrate container exits before the database has even started. Not sure if there's something wrong with the `depends_on` syntax or what. I have a lot of other projects to work on today and I've spent way to many hours working on crystal this week. 

If I can solve docker soon I'm just going to send a pull request for my sqlite fix which also works in docker, and let someone who understands docker-compose a bit better try to fix this. I'm hoping that's you.

**Comment by drujensen** [comment]
Sounds good. The depends_on option doesn't wait for the port to open. I will look at adding a check to wait for the port to open before migrating. 

Looking forward to the SQLite support.

**Comment by elorest** [comment]
I reverted back to the postgres only version of the docker-compose and it
still doesn't work. Then I tried it on my other computer and it worked 3
times and then stopped. I wonder if it has to do with how we're storing the
volume locally or something... I'm going to commit my
docker-compose.yml.ecr that should work with everything as
`docker-compose.yml.wip.ecr` in the sqlite PR.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005

**Comment by elorest** [comment]
Perhaps something like this could be useful.
https://github.com/vishnubob/wait-for-it

**Comment by drujensen** [comment]
@elorest this should now be fixed.  let me know if you still run into any issues.

**Comment by drujensen** [comment]
darn, worked locally but now having issues.

**Comment by drujensen** [comment]
minor fix.  should be good now.

**Comment by elorest** [comment]
LOL. Yeah I had nightmares about that bug last night. So frustrating when
it would start working randomly and then stop.

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005
