### ISSUE TITLE
Mysql db errors (but still works)

### ISSUE THREAD

**Issue by drujensen** [TechMagister/kemalyst-generator#39]
The mysql db connection in the docker-compose is throwing communication errors.
```
web_1      | I, [2017-04-17 04:36:55 +0000 #224]  INFO -- : 018e800c-6c08-4a03-b329-0675f87bc2fa 200 | GET /posts | 3.08ms
web_1      | I, [2017-04-17 04:37:04 +0000 #224]  INFO -- : b32b6237-ddd1-439e-a294-092770e148d9 200 | GET /posts/new | 1.54ms
db_1       | 2017-04-17T04:37:35.059229Z 16 [Note] Aborted connection 16 to db: 'blog_development' user: 'admin' host: '172.20.0.3' (Got an error reading communication packets)
```

**Comment by elorest** [comment]
I think that's possibly and issue with pooling. Possibly the mysql docker container has max connections set at 4 or something.

**Comment by elorest** [comment]
I set my docker container to just connect to a local copy of mysql and it didn't give any issues. Pretty sure something is weird with max connections on _/mysql

**Comment by drujensen** [comment]
what version of mysql?  Maybe we can use that instead of the latest.
