### ISSUE TITLE
Migrations run without printing messages.

### ISSUE THREAD

**Issue by elorest** [TechMagister/kemalyst-generator#41]
In the past `kgen m up` would print out which migrations it ran. For some reason it stopped doing that now.

**Comment by drujensen** [comment]
Added this back: https://github.com/TechMagister/kemalyst-generator/commit/fb45bcfb8cb6ccd054206c7ec4b823e839a5c6f9#diff-71b34f60d46f08420efc6584f0bbd043R18

Should be fixed.
