### ISSUE TITLE
brew install kgen

### ISSUE THREAD

**Issue by drujensen** [TechMagister/kemalyst-generator#5]
What do you think of supporting kgen from the command line similar to fez?

**Comment by TechMagister** [comment]
Yes, I thinks it's necessary to generate new projects with custom template and there is no reason to keep one installation by project.

**Comment by drujensen** [comment]
Awesome.  I will take a look at this today.

**Comment by drujensen** [comment]
https://github.com/TechMagister/kemalyst-generator/pull/16

**Comment by TechMagister** [comment]
Good job !  :gift:
