### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by lebogan** [TechMagister/kemalyst-generator#58]
Hello, in attempting to install, I ran into two problems:

1. git clone git@github... from the README fails with a fatal error.
    git clone https://github... works. Please, update the README.
2. make fails with this error:
    Error in src/kemalyst-generator.cr:1: while requiring "cli"
    require "cli"
    in lib/cli/src/cli.cr:8: while requiring "./cli/ios/*"
    require "./cli/ios/*"
    in lib/cli/src/cli/ios/pipe.cr:9: ***IO is not a module, it's a class***
    include IO
            ^~
    make: *** [Makefile:8: build] Error 1

I am using crystal 0.24.1 on a fedora 26 vagrant image. Thanks for considering this issue. I really want to try this generator.

**Comment by drujensen** [comment]
Hi @lebogan This project is no longer being maintained.  Kemalyst is now merged into Amber https://amberframework.org.
